# Generated by Django 3.1.1 on 2020-09-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no_pgs', models.IntegerField()),
                ('price', models.IntegerField(default=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lib_mgmt_sys.author')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPenName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=56)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='lib_mgmt_sys.author')),
            ],
        ),
    ]
