# Generated by Django 3.1.1 on 2020-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_mgmt_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField()),
                ('booked', models.ManyToManyField(to='lib_mgmt_sys.Books')),
            ],
        ),
    ]
